/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cy_pdl.h"
#include "cyhal.h"
#include "cybsp.h"
#include "secure_config.h"
#include "shared.h"

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/**********************************************************************************************************************
 * Function Name: main
 * Summary:
 *  This is the main function.
 * Parameters:
 *  none
 * Retrun:
 *  int
 **********************************************************************************************************************
 */
int main(void)
{
    cy_rslt_t                   halResult;
    API_ARGS_Type               apiArg;
    RW_SWPU_DATA_Type           apiData;
    un_srom_api_resps_t         apiResp;
    cy_en_srom_driver_status_t  apiResult;

    /* Enable global interrupts */
    __enable_irq();

    for (;;)
    {
        /* Check request and perform it if there */
        if ((g_shared[FROM_CM0_TO_CM7_0] == FROM_CM0_ERASE_SECTOR127) ||
            (g_shared[FROM_CM0_TO_CM7_0] == FROM_CM0_ERASE_SECTOR128))
        {
            halResult = cyhal_flash_erase(
                            &g_flash,
                            (g_shared[FROM_CM0_TO_CM7_0] == FROM_CM0_ERASE_SECTOR127) ? SECTOR127_ADDR : SECTOR128_ADDR);

            if (halResult == CY_RSLT_SUCCESS)
            {
                g_shared[FROM_CM7_0_TO_CM0] = (uint32_t)"cyhal_flash_erase() has been successfully finished!";
            }
            else
            {
                g_shared[FROM_CM7_0_TO_CM0] = (uint32_t)"cyhal_flash_erase() has been failed..";
            }
            g_shared[FROM_CM0_TO_CM7_0] = 0;
        }
        else if ((g_shared[FROM_CM0_TO_CM7_0] == FROM_CM0_ENABLE_CM7_1_ACCESS) ||
                 (g_shared[FROM_CM0_TO_CM7_0] == FROM_CM0_DISABLE_CM7_1_ACCESS))
        {
            apiArg.r.opCode     = 0x2C;                 /* ReadSWPU */
            apiArg.r.puType     = 0;                    /* Flash Write */
            apiArg.r.puId       = 1;                    /* for sector 128 is included in index 1 */
            apiArg.r.dataAddr   = (uint32_t)&apiData;   /* SRAM_DATA_ADDRESS */
            apiResult = Cy_Srom_CallApi((un_srom_api_args_t *)&apiArg, &apiResp);

            if ((apiResult == CY_SROM_DR_SUCCEEDED) &&
                ((apiResp.resp[0] & API_RESULT_MASK) == API_RESULT_SUCCESS))
            {
                apiArg.w.opCode         = 0x2D;         /* WriteSWPU */
                apiArg.w.control        = 0;            /* Update SWPU */
                apiArg.w.puType         = 0;            /* Flash Write */
                apiArg.w.puId           = 1;            /* for sector 128 is included in index 1 */
                apiArg.w.dataAddr       = (uint32_t)&apiData;
                apiData.slAtt.pcMask = (g_shared[FROM_CM0_TO_CM7_0] == FROM_CM0_ENABLE_CM7_1_ACCESS) ? 0x00FF : 0x007F;
                apiResult = Cy_Srom_CallApi((un_srom_api_args_t *)&apiArg, &apiResp);

                if ((apiResult == CY_SROM_DR_SUCCEEDED) &&
                    ((apiResp.resp[0] & API_RESULT_MASK) == API_RESULT_SUCCESS))
                {
                    g_shared[FROM_CM7_0_TO_CM0] = (uint32_t)"Cy_Srom_CallApi() for WriteSWPU has been successfully finished!";
                }
                else
                {
                    g_shared[FROM_CM7_0_TO_CM0] = (uint32_t)"Cy_Srom_CallApi() for WriteSWPU has been failed..";
                }
            }
            else
            {
                g_shared[FROM_CM7_0_TO_CM0] = (uint32_t)"Cy_Srom_CallApi() for ReadSWPU has been failed..";
            }
            g_shared[FROM_CM0_TO_CM7_0] = 0;
        }
        else
        {
            /* Delay between next read */
            cyhal_system_delay_ms(DELAY_BETWEEN_READ_MS);
        }
    }
}

/* [] END OF FILE */
