/**********************************************************************************************************************
 * \file shared.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef SHARED_H
#define SHARED_H

#if defined(__cplusplus)
extern "C" {
#endif

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
enum
{
    FROM_CM0_TO_CM7_0 = 0,
    FROM_CM7_0_TO_CM0,
    FROM_CM0_TO_CM7_1,
    FROM_CM7_1_TO_CM0,
    SHARED_NUM
};

enum
{
    FROM_CM0_ERASE_SECTOR127 = 1,
    FROM_CM0_WRITE_SECTOR127,
    FROM_CM0_ERASE_SECTOR128,
    FROM_CM0_WRITE_SECTOR128,
    FROM_CM0_ENABLE_CM7_1_ACCESS,
    FROM_CM0_DISABLE_CM7_1_ACCESS,
};

#define DELAY_BETWEEN_READ_MS   (100)

#define SECTOR127_ADDR          (0x103F8000)
#define SECTOR128_ADDR          (0x10400000)
#define SECTOR_SIZE             (0x00008000)

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
CY_SECTION(".shared") uint32_t g_shared[SHARED_NUM];
CY_SECTION(".shared") cyhal_flash_t g_flash;

#if defined(__cplusplus)
}
#endif

#endif /* SHARED_H */

/* [] END OF FILE */
