/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cy_pdl.h"
#include "cyhal.h"
#include "cybsp.h"
#include "cy_retarget_io.h"
#include "secure_config.h"
#include "shared.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define UART_IRQ_PRIORITY   (3)

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* becomes true when rx data comes */
volatile bool g_uartReadFlag = false;

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
CY_SECTION(".cy_sflash_app_prot") __USED static const SFLASH_APP_PROT_Type SI_APPPROT = 
{
    .objSize                = OBJECT_SIZE,              /* Application Protection Object Size (in bytes) */
    .nFWPU                  = N_FWPU,                   /* Number of FWPU Max 16 */

    .FWPU0Adr.addr30        = SECTOR127_ADDR>>2ul,      /* Region address */
    .FWPU0Size.regionSize   = SECTOR_SIZE,              /* in bytes (multiple of 4) */
    .FWPU0Size.enable       = APP_PROT_ENABLE,          /* FWPU0 enable */
    .FWPU0SlAtt.urw         = APP_PROT_ALLOW,           /* FWPU0 Slave Attribute */
    .FWPU0SlAtt.prw         = APP_PROT_ALLOW,           /* FWPU0 Slave Attribute */
    .FWPU0SlAtt.ns          = APP_PROT_ALLOW,           /* FWPU0 Slave Attribute */
    .FWPU0SlAtt.pcMask      = 0x003F,                   /* FWPU0 Slave Attribute */
                                                        /* bit0: PC0 mask (0: Prohibit, 1: Allow) */
                                                        /*  :                                     */
                                                        /* bit7: PC7 mask                         */
                                                        /* bit[8:15]: 0 */
    .FWPU0MsAtt.urw         = APP_PROT_ALLOW,           /* FWPU0 Master Attribute */
    .FWPU0MsAtt.prw         = APP_PROT_ALLOW,           /* FWPU0 Master Attribute */
    .FWPU0MsAtt.ns          = APP_PROT_ALLOW,           /* FWPU0 Master Attribute */
    .FWPU0MsAtt.pcMask      = 0x003F,                   /* FWPU0 Master Attribute */

    .FWPU1Adr.addr30        = SECTOR128_ADDR>>2ul,      /* Region address */
    .FWPU1Size.regionSize   = SECTOR_SIZE,              /* in bytes (multiple of 4) */
    .FWPU1Size.enable       = APP_PROT_ENABLE,          /* FWPU1 enable */
    .FWPU1SlAtt.urw         = APP_PROT_ALLOW,           /* FWPU1 Slave Attribute */
    .FWPU1SlAtt.prw         = APP_PROT_ALLOW,           /* FWPU1 Slave Attribute */
    .FWPU1SlAtt.ns          = APP_PROT_ALLOW,           /* FWPU1 Slave Attribute */
    .FWPU1SlAtt.pcMask      = 0x007F,                   /* FWPU1 Slave Attribute */
                                                        /* bit0: PC0 mask (0: Prohibit, 1: Allow) */
                                                        /*  :                                     */
                                                        /* bit7: PC7 mask                         */
                                                        /* bit[8:15]: 0 */
    .FWPU1MsAtt.urw         = APP_PROT_ALLOW,           /* FWPU1 Master Attribute */
    .FWPU1MsAtt.prw         = APP_PROT_ALLOW,           /* FWPU1 Master Attribute */
    .FWPU1MsAtt.ns          = APP_PROT_ALLOW,           /* FWPU1 Master Attribute */
    .FWPU1MsAtt.pcMask      = 0x007F,                   /* FWPU1 Master Attribute */
};

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/**********************************************************************************************************************
 * Function Name: handleUartEvent
 * Summary:
 *  UART event handler callback function. Sets the read flag to true upon successful reception of data.
 * Parameters:
 *  handlerArg - argument for the handler provided during callback registration
 *  event - interrupt cause flags
 * Retrun:
 *  void
 **********************************************************************************************************************
 */
void handleUartEvent(void *handlerArg, cyhal_uart_event_t event)
{
    (void)handlerArg;

    if (CYHAL_UART_IRQ_RX_DONE == (event & CYHAL_UART_IRQ_RX_DONE))
    {
        /* Set read flag */
        g_uartReadFlag = true;
    }
    else
    {
        CY_ASSERT(0);
    }
}

/**********************************************************************************************************************
 * Function Name: printInstructions
 * Summary:
 *  Prints set of instructions.
 * Parameters:
 *  void
 * Retrun:
 *  void
 **********************************************************************************************************************
 */
void printInstructions(void)
{
    printf("====================================================\r\n"
           "Instructions:\r\n"
           "====================================================\r\n"
           "Press '0' : To make the CM7_0 erases the sector 127\r\n"
           "Press '1' : To make the CM7_0 erases the sector 128\r\n"
           "Press '2' : To make the CM7_1 writes the sector 127\r\n"
           "Press '3' : To make the CM7_1 writes the sector 128\r\n"
           "Press '4' : To enable the CM7_1 access to sector 128 by CM7_0\r\n"
           "Press '5' : To disable the CM7_1 access to sector 128 by CM7_0\r\n"
           "====================================================\r\n");
}

/**********************************************************************************************************************
 * Function Name: processKeyPress
 * Summary:
 *  Function to process the key pressed.
 *  Depending on the command passed as parameter, the process to be performed is selected.
 * Parameters:
 *  keyPressed - command read through terminal
 * Retrun:
 *  The core number to wait for response at caller (-1 means no need to wait)
 **********************************************************************************************************************
 */
int8_t processKeyPress(char keyPressed)
{
    int8_t tobeWait = -1;

    printf("Pressed key: %c\r\n", keyPressed);

    switch (keyPressed)
    {
    /* Press '0' : To make the CM7_0 erases the sector 127 */
    case '0':
        g_shared[FROM_CM0_TO_CM7_0] = FROM_CM0_ERASE_SECTOR127;
        tobeWait = 0;
        break;
    /* Press '1' : To make the CM7_0 erases the sector 128 */
    case '1':
        g_shared[FROM_CM0_TO_CM7_0] = FROM_CM0_ERASE_SECTOR128;
        tobeWait = 0;
        break;
    /* Press '2' : To make the CM7_1 writes the sector 127 */
    case '2':
        g_shared[FROM_CM0_TO_CM7_1] = FROM_CM0_WRITE_SECTOR127;
        tobeWait = 1;
        break;
    /* Press '3' : To make the CM7_1 writes the sector 128 */
    case '3':
        g_shared[FROM_CM0_TO_CM7_1] = FROM_CM0_WRITE_SECTOR128;
        tobeWait = 1;
        break;
    /* Press '4' : To enable the CM7_1 access to sector 128 by CM7_0 */
    case '4':
        g_shared[FROM_CM0_TO_CM7_0] = FROM_CM0_ENABLE_CM7_1_ACCESS;
        tobeWait = 0;
        break;
    /* Press '5' : To disable the CM7_1 access to sector 128 by CM7_0 */
    case '5':
        g_shared[FROM_CM0_TO_CM7_0] = FROM_CM0_DISABLE_CM7_1_ACCESS;
        tobeWait = 0;
        break;
    default:
        printf("Wrong key pressed !! See below instructions:\r\n");
        printInstructions();
        break;
    }

    return tobeWait;
}

/**********************************************************************************************************************
 * Function Name: main
 * Summary:
 *  This is the main function.
 * Parameters:
 *  none
 * Retrun:
 *  int
 **********************************************************************************************************************
 */
int main(void)
{
    char uartReadValue;

    /* Initialize the device and board peripherals */
    if (cybsp_init() != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Initialize retarget-io to use the debug UART port */
    if (cy_retarget_io_init(CYBSP_DEBUG_UART_TX, CYBSP_DEBUG_UART_RX, CY_RETARGET_IO_BAUDRATE) != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* The UART callback handler registration */
    cyhal_uart_register_callback(&cy_retarget_io_uart_obj, handleUartEvent, NULL);

    /* Enable UART events to get notified on receiving
     * RX data and on RX errors */
    cyhal_uart_enable_event(&cy_retarget_io_uart_obj,
                            (cyhal_uart_event_t)(CYHAL_UART_IRQ_RX_ERROR | CYHAL_UART_IRQ_RX_DONE),
                            UART_IRQ_PRIORITY, true);

    /* Flash initialization */
    if (cyhal_flash_init(&g_flash) != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Enable code flash write function */
    Cy_Flashc_MainWriteEnable();

    /* enable interrupts */
    __enable_irq();

    /* \x1b[2J\x1b[;H - ANSI ESC sequence for clear screen */
    printf("\x1b[2J\x1b[;H");

    printf("****************** "
           "code example of SWPU application protection "
           "****************** \r\n\n");

    /* set PC for CM7_0/1 */
    if (Cy_Prot_ConfigBusMaster(CPUSS_MS_ID_CM7_0, true, true, CY_PROT_PCMASK6) != CY_PROT_SUCCESS)
    {
        CY_ASSERT(0);
    }
    if (Cy_Prot_SetActivePC(CPUSS_MS_ID_CM7_0, CY_PROT_PC6) != CY_PROT_SUCCESS)
    {
        CY_ASSERT(0);
    }
    if (Cy_Prot_ConfigBusMaster(CPUSS_MS_ID_CM7_1, true, true, CY_PROT_PCMASK7) != CY_PROT_SUCCESS)
    {
        CY_ASSERT(0);
    }
    if (Cy_Prot_SetActivePC(CPUSS_MS_ID_CM7_1, CY_PROT_PC7) != CY_PROT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Clear shared data */
    memset(g_shared, 0, sizeof(g_shared));

    /* Enable CM7_0/1. CY_CORTEX_M7_APPL_ADDR is calculated in linker script, check it in case of problems. */
    Cy_SysEnableCM7(CORE_CM7_0, CY_CORTEX_M7_0_APPL_ADDR);
    Cy_SysEnableCM7(CORE_CM7_1, CY_CORTEX_M7_1_APPL_ADDR);

    /* Display instructions */
    printInstructions();

    for (;;)
    {
        /* Begin asynchronous RX read */
        cyhal_uart_read_async(&cy_retarget_io_uart_obj, (void*) &uartReadValue, sizeof(uartReadValue));

        /* Check if the read flag has been set by the callback */
        if (g_uartReadFlag)
        {
            /* Clear read flag */
            g_uartReadFlag = false;

            /* Process the command */
            int8_t tobeWait = processKeyPress(uartReadValue);

            /* Waiting for the response from CM7_0/1 */
            if (tobeWait != (-1))
            {
                uint32_t *pRsp = ((tobeWait == 0) ? &g_shared[FROM_CM7_0_TO_CM0] : &g_shared[FROM_CM7_1_TO_CM0]);
                *pRsp = 0;
                while (*pRsp == 0)
                {
                    cyhal_system_delay_ms(DELAY_BETWEEN_READ_MS);
                }
                /* Display the string from CM7_0/1 */
                printf("CM7_%d reports: %s\r\n\r\n", tobeWait, (char *)*pRsp);
            }
        }

        /* Delay between next read */
        cyhal_system_delay_ms(DELAY_BETWEEN_READ_MS);
    }

    return 0;
}

/* [] END OF FILE */
